# Generated by Django 3.2 on 2023-05-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('postcode', models.IntegerField(verbose_name='Почтовый индекс')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='events/')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('organizations', models.ManyToManyField(related_name='organizations', to='events.Organization', verbose_name='Организации')),
            ],
        ),
    ]
